import type { Metadata } from "next";
import { Footer } from "@/components/universal/footer";
import { Navbar } from "@/components/universal/navbar"; // import "@uploadthing/react/styles.css";

export const metadata: Metadata = {
  title: "Sportsverein Schlossberg",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen bg-[#f0f4f0]">
      <Navbar />
      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  );
}
